### ISSUE TITLE
Apollo Studio introspection - headers don't use environment variable substution

### ISSUE THREAD

**Issue by charles-hill-exelon** [apollographql/apollo-studio-community#118]
Apollo Studio is sending the introspection query with headers, but not doing environment variable substitution.  Normal queries are applying the environment variables correctly.

Studio config:
![Screen Shot 2021-11-05 at 11 03 09 AM](https://user-images.githubusercontent.com/33763774/140532435-fa624957-ca9b-4f53-b7fa-c2b4d966c5ba.png)

![Screen Shot 2021-11-05 at 11 03 26 AM](https://user-images.githubusercontent.com/33763774/140532461-fe851c41-1f86-4901-98d3-3856a9b3d1c3.png)

What the server is getting:
![Screen Shot 2021-11-05 at 11 03 35 AM](https://user-images.githubusercontent.com/33763774/140532474-2b0f2e88-e143-46bd-a9a0-411e7c7f4ae6.png)

**Comment by cheapsteak** [comment]
Thank you for the report! looks like a bug, we'll look into this :)

**Comment by mayakoneval** [comment]
This should be fixed in the newest version of Studio. If you are logged in, you can click on your avatar at the top right, and then click on "Update available, click to relaunch". If you are not logged in, you can click on the speaker icon in the top right, and then click on "Update available, click to relaunch" at the bottom left of the modal.
