### ISSUE TITLE
Dark mode default system preferences

### ISSUE THREAD

**Issue by babakfp** [apollographql/apollo-studio-community#119]
Hi
My system preferences are on dark mode. So I shouldn't look for a dark mode option.
![Annotation 2021-11-13 235153](https://user-images.githubusercontent.com/44144724/141658000-7eca79d1-8c1a-4a64-a637-51e86f8cee34.png)
Thanks

**Comment by babakfp** [comment]
Currently, I'm not using this tool or anything related but was is the status of this issue? As far as I know, this is an easy CSS fix🤔🌸.
@mayakoneval

**Comment by mayakoneval** [comment]
Hi @babakfp, 

Apologies for the late response! We actually did build this into Studio since you first messaged. Now, when you first come to studio, if your system preferences are on dark mode, Studio will be in dark mode. However, since you have touched the dark mode slider already, the theming is now 100% up to you. 

Let me know if you have any other questions!
Maya

**Comment by cheapsteak** [comment]
Closing the issue as resolved, let us know if it continues to be a problem :)
