### ISSUE TITLE
Introspection query doesn't include cookies even if we enable the option

### ISSUE THREAD

**Issue by alaarihan** [apollographql/apollo-studio-community#88]
Hi,

I noticed that Apollo Studio doesn't send browser cookies with the Introspection query request even if I make "Include cookies" option on but it includes them for the other queries.

**Comment by cuzzlor** [comment]
Wow, this was maddening.

If configuring CORS and local dev TLS in order to be able to use SameSite=None; Secure wasn't fun enough, to eventually find out the cookies feature doesn't actually work (what good is this tool without introspection?).

It was only this issue (thankyou for posting) which made me finally realise (after wasting much time) that I wasn't doing anything wrong, I can issue a query OK (cookies are included) but the introspection poll fails (cookies are not included).

**Comment by cuzzlor** [comment]
Introspection queries are auth'd for me now!

**Comment by daniman** [comment]
Hey @cuzzlor, I'm going to close this for now since it sounds like you've figured it out! We did have a bug where cookies weren't sent along with introspection requests, but I believe it has since been resolved.
